<a href="https://colab.research.google.com/github/kirat89/Google_colab/blob/main/Bank_retention_model_using_ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [25]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [26]:
tf.__version__

'2.6.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [27]:
data=pd.read_csv('Churn_Modelling.csv')
X=data.iloc[:,3:-1].values
Y=data.iloc[:,-1].values

In [28]:
print(X)
print(Y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [29]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

One Hot Encoding the "Geography" column

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))



In [31]:
pd.DataFrame(X)

0  1  2    3  4   5   6        7  8  9  10       11
0     1  0  0  619  0  42   2        0  1  1  1   101349
1     0  0  1  608  0  41   1  83807.9  1  0  1   112543
2     1  0  0  502  0  42   8   159661  3  1  0   113932
3     1  0  0  699  0  39   1        0  2  0  0  93826.6
4     0  0  1  850  0  43   2   125511  1  1  1  79084.1
...  .. .. ..  ... ..  ..  ..      ... .. .. ..      ...
9995  1  0  0  771  1  39   5        0  2  1  0  96270.6
9996  1  0  0  516  1  35  10  57369.6  1  1  1   101700
9997  1  0  0  709  0  36   7        0  1  0  1  42085.6
9998  0  1  0  772  1  42   3  75075.3  2  1  0  92888.5
9999  1  0  0  792  0  28   4   130143  1  1  0  38190.8

[10000 rows x 12 columns]

### Splitting the dataset into the Training set and Test set

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.2,random_state=1)

### Feature Scaling

In [33]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
ss.fit(X_train)
X_train=ss.transform(X_train)
X_test=ss.transform(X_test)
 

## Part 2 - Building the ANN

### Initializing the ANN

In [34]:
ann=tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [36]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the second hidden layer

In [37]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the output layer

In [38]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [39]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

### Training the ANN on the Training set

In [40]:
ann.fit(X_train,Y_train,batch_size=32,epochs=50)

Epoch 1/50
250/250 [==============================] - 1s 1ms/step - loss: 0.5701 - accuracy: 0.7341
Epoch 2/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4740 - accuracy: 0.7984
Epoch 3/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4371 - accuracy: 0.8064
Epoch 4/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4128 - accuracy: 0.8245
Epoch 5/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3945 - accuracy: 0.8372
Epoch 6/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3809 - accuracy: 0.8464
Epoch 7/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3712 - accuracy: 0.8505
Epoch 8/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3645 - accuracy: 0.8516
Epoch 9/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3605 - accuracy: 0.8497
Epoch 10/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3564 - accuracy: 0.8526

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Solution**

In [41]:
print(ann.predict(ss.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


### Predicting the Test set results

In [54]:
pred= ann.predict(X_test)

In [55]:
pred=(pred>.5)
print(np.concatenate((pred.reshape(len(pred),1),Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [56]:
from sklearn.metrics import accuracy_score
score=accuracy_score(Y_test,pred)
print(score)

0.8635


In [57]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,pred)
print(cm)


[[1527   58]
 [ 215  200]]
